name: S3 Deploy
on:
  push:
    branches:
      - "main"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      name: Production
      AWS_ACCESS_KEY_ID: ${{ secrets.AMAZON_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build React
        run: npm run build
      - name: Upload to S3
        needs: build
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          folder: build
          bucket: ${{ secrets.AMAZON_S3_BUCKET }}
          bucket-region: eu-west-1
          delete-removed: true
          no-cache: true
          private: true
